name: Test Then Build

on:
  workflow_call:
    inputs:
      PROJECT: 
        required: true
        type: string

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Test
      run: go test -v ./...

  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag ${{ inputs.PROJECT }}:$(date +%s)
